name: Test Guess the Flag

on: 
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Set up python3
      uses: actions/setup_python@v3
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest

